### ISSUE TITLE
Draft.insert not the same as table.insert

### ISSUE THREAD

**Issue by ShouxTech** [SolarHorizon/immut#5]
Draft.insert only reflects the 3 parameter definition of table.insert (function insert(t: table, pos: number, value: any)). It would be a lot nicer to work with Draft.insert if it also had the option for the 2 parameter definition of table.insert (function insert(t: table, value: any)).

Current usage:
Draft.insert(tbl, #tbl + 1, data)

Desired usage:
Draft.insert(tbl, data)

**Comment by tracyspells** [comment]
support! would love to see this implemented

**Comment by SolarHorizon** [comment]
You are already able to use it this way. The type for `Immut.insert` is `<V>(draft: {V}, pos: number | V, value: V?)`. 

The second argument can be either the value you want to insert or the position of the value in the array. Internally it's just taking the arguments you pass into the draft-safe insert and passing them through to `table.insert`, so in terms of behavior, it's 1:1.

It is a little confusing because I have to cram this all into one type since Luau does not currently allow users to create overloaded function types (see the note at the end https://luau-lang.org/typecheck#intersection-types)

If there's some other issue with this that I'm missing let me know, but it should be perfectly fine to use in the way you're suggesting.

**Comment by tracyspells** [comment]
I'm glad that we're able to use it that way, but I've tried doing it and I got this:

![3](https://user-images.githubusercontent.com/84782396/232335032-fa0de22c-8043-4b80-b019-4b114c7e6b6e.PNG)
